services:
  app:
    build: .
    container_name: dialogflow-webhook-example
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:/code
